services:
  linklet:
    build: .
    container_name: linklet
    hostname: linklet
    ports:
      - "8002:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - DATA_FILE=/app/urls.json
      - VISITS_FILE=/app/visits.jsonl
    volumes:
      - ./urls.json:/app/urls.json
      - ./visits.jsonl:/app/visits.jsonl
    restart: always
